"""foreignkeys1

Revision ID: 1022ade487ff
Revises: fb201b7fdb8f
Create Date: 2026-01-17 14:56:01.127001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1022ade487ff'
down_revision: Union[str, Sequence[str], None] = 'fb201b7fdb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prenotazioni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stato', sa.Enum('prenotata', 'completata', 'annullata', name='stato_prenotazione'), nullable=False),
    sa.Column('data_visita', sa.Date(), nullable=False),
    sa.Column('ora_visita', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('reparto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paziente_id'], ['pazienti.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('reparti', 'piano',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reparti', 'piano',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('prenotazioni')
    # ### end Alembic commands ###
