"""account_table

Revision ID: 11eb9bf2cd86
Revises: 4f6ac5dfbc20
Create Date: 2026-02-07 16:49:45.237791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11eb9bf2cd86'
down_revision: Union[str, Sequence[str], None] = '4f6ac5dfbc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('pazienti', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pazienti', 'accounts', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pazienti', type_='foreignkey')
    op.drop_column('pazienti', 'account_id')
    op.drop_table('accounts')
    # ### end Alembic commands ###
