"""prenotazioneid

Revision ID: 156fbc1658c9
Revises: 5f9836ca13dc
Create Date: 2026-02-05 17:55:22.257392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156fbc1658c9'
down_revision: Union[str, Sequence[str], None] = '5f9836ca13dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referti', sa.Column('prenotazione_id', sa.Integer(), nullable=True)) #era false ho messo true
    op.alter_column('referti', 'titolo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'referti', ['prenotazione_id'])
    op.create_foreign_key(None, 'referti', 'prenotazioni', ['prenotazione_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referti', type_='foreignkey')
    op.drop_constraint(None, 'referti', type_='unique')
    op.alter_column('referti', 'titolo',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('referti', 'prenotazione_id')
    # ### end Alembic commands ###
