"""medico n

Revision ID: 1c0ae46028b3
Revises: e09a24ab25a9
Create Date: 2026-03-04 18:15:10.161994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0ae46028b3'
down_revision: Union[str, Sequence[str], None] = 'e09a24ab25a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medici', 'specializzazione',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medici', 'n_telefono',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medici', 'n_telefono',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medici', 'specializzazione',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
