"""titolo

Revision ID: 1d1c54342a0b
Revises: 61262bb1dbc5
Create Date: 2026-02-02 16:16:49.049216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1c54342a0b'
down_revision: Union[str, Sequence[str], None] = '61262bb1dbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referti', sa.Column('titolo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referti', 'titolo')
    # ### end Alembic commands ###
