"""associazione mr2

Revision ID: 1f7581c79345
Revises: 375f0bc00476
Create Date: 2026-03-16 19:14:32.855291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7581c79345'
down_revision: Union[str, Sequence[str], None] = '375f0bc00476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medici_reparti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medici_reparti',
    sa.Column('medico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reparto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], name=op.f('medici_reparti_medico_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], name=op.f('medici_reparti_reparto_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medico_id', 'reparto_id', name=op.f('medici_reparti_pkey'))
    )
    # ### end Alembic commands ###
