"""tabellaPazienti1

Revision ID: 2565f5208f72
Revises: 
Create Date: 2026-01-15 16:01:11.537538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2565f5208f72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pazienti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('cognome', sa.Text(), nullable=False),
    sa.Column('codice_fiscale', sa.Text(), nullable=False),
    sa.Column('data_nascita', sa.Date(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('n_telefono', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('n_telefono')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pazienti')
    # ### end Alembic commands ###
