"""medico cf

Revision ID: 319b491772c4
Revises: 67091ec2f9e1
Create Date: 2026-03-04 17:49:43.450917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319b491772c4'
down_revision: Union[str, Sequence[str], None] = '67091ec2f9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medici', sa.Column('codice_fiscale', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'medici', ['codice_fiscale'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medici', type_='unique')
    op.drop_column('medici', 'codice_fiscale')
    # ### end Alembic commands ###
