"""associazione mr

Revision ID: 375f0bc00476
Revises: 45b08fdc7ef2
Create Date: 2026-03-16 18:42:01.330581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375f0bc00476'
down_revision: Union[str, Sequence[str], None] = '45b08fdc7ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medici_reparti',
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('reparto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medico_id', 'reparto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medici_reparti')
    # ### end Alembic commands ###
