"""appu

Revision ID: 3af773913863
Revises: c672fa3b65e3
Create Date: 2026-01-27 19:25:18.546288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af773913863'
down_revision: Union[str, Sequence[str], None] = 'c672fa3b65e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilita_medici',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('giorno_settimana', sa.Integer(), nullable=False),
    sa.Column('ora_inizio', sa.Time(), nullable=False),
    sa.Column('ora_fine', sa.Time(), nullable=False),
    sa.Column('durata_slot', sa.Integer(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disponibilita_medici')
    # ### end Alembic commands ###
