"""aggiornamenti

Revision ID: 45b08fdc7ef2
Revises: ebed0d742236
Create Date: 2026-03-13 16:56:25.535229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b08fdc7ef2'
down_revision: Union[str, Sequence[str], None] = 'ebed0d742236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prenotazioni', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prenotazioni', 'updated_at')
    # ### end Alembic commands ###
