"""prenotazioneid3

Revision ID: 4f6ac5dfbc20
Revises: eff1f13e0396
Create Date: 2026-02-05 18:19:48.675583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6ac5dfbc20'
down_revision: Union[str, Sequence[str], None] = 'eff1f13e0396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
