"""refertistato

Revision ID: 5f58ddc35e4b
Revises: 742a3002c6a5
Create Date: 2026-01-21 17:37:44.132933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f58ddc35e4b"
down_revision: Union[str, Sequence[str], None] = "742a3002c6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("referti", sa.Column("aperto", sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referti", "aperto")
    # ### end Alembic commands ###
