"""titolo4

Revision ID: 5f9836ca13dc
Revises: b88a6d4761b2
Create Date: 2026-02-02 17:11:18.036358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9836ca13dc'
down_revision: Union[str, Sequence[str], None] = 'b88a6d4761b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referti', 'titolo',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referti', 'titolo',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
