"""note_prenotazione

Revision ID: 61262bb1dbc5
Revises: 3af773913863
Create Date: 2026-01-29 17:14:56.471823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61262bb1dbc5'
down_revision: Union[str, Sequence[str], None] = '3af773913863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prenotazioni', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prenotazioni', 'note')
    # ### end Alembic commands ###
