"""medico account id

Revision ID: 67091ec2f9e1
Revises: ecb2afd0aa51
Create Date: 2026-03-04 15:30:42.916756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67091ec2f9e1'
down_revision: Union[str, Sequence[str], None] = 'ecb2afd0aa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medici', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'medici', ['account_id'])
    op.create_foreign_key(None, 'medici', 'accounts', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medici', type_='foreignkey')
    op.drop_constraint(None, 'medici', type_='unique')
    op.drop_column('medici', 'account_id')
    # ### end Alembic commands ###
