"""referti1

Revision ID: 742a3002c6a5
Revises: c1658c9ec780
Create Date: 2026-01-20 18:47:20.430387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742a3002c6a5'
down_revision: Union[str, Sequence[str], None] = 'c1658c9ec780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pressione_min', sa.Integer(), nullable=True),
    sa.Column('pressione_max', sa.Integer(), nullable=True),
    sa.Column('freq_cardiaca', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paziente_id'], ['pazienti.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referti')
    # ### end Alembic commands ###
