"""profilo4 e autogenerate

Revision ID: 8c48d8933212
Revises: 5c7b84145242
Create Date: 2026-02-20 17:56:41.335519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c48d8933212'
down_revision: Union[str, Sequence[str], None] = '5c7b84145242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condizioni_croniche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_condizione', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_condizione')
    )
    op.create_table('allergie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_allergia', sa.String(length=100), nullable=False),
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paziente_id'], ['pazienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatti_emergenza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('relazione', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paziente_id'], ['pazienti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paziente_condizioni',
    sa.Column('paziente_id', sa.Integer(), nullable=False),
    sa.Column('condizione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condizione_id'], ['condizioni_croniche.id'], ),
    sa.ForeignKeyConstraint(['paziente_id'], ['pazienti.id'], ),
    sa.PrimaryKeyConstraint('paziente_id', 'condizione_id')
    )
    op.add_column('pazienti', sa.Column('eta', sa.Integer(), nullable=True))
    op.add_column('pazienti', sa.Column('gruppo_sanguigno', sa.Text(), nullable=True))
    op.add_column('pazienti', sa.Column('altezza', sa.Float(), nullable=True))
    op.add_column('pazienti', sa.Column('peso', sa.Integer(), nullable=True))
    op.add_column('pazienti', sa.Column('indirizzo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pazienti', 'indirizzo')
    op.drop_column('pazienti', 'peso')
    op.drop_column('pazienti', 'altezza')
    op.drop_column('pazienti', 'gruppo_sanguigno')
    op.drop_column('pazienti', 'eta')
    op.drop_table('paziente_condizioni')
    op.drop_table('contatti_emergenza')
    op.drop_table('allergie')
    op.drop_table('condizioni_croniche')
    # ### end Alembic commands ###
