"""role

Revision ID: 8e0aec7c4d60
Revises: ece472a6a39d
Create Date: 2026-02-09 19:48:37.648689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '8e0aec7c4d60'
down_revision: Union[str, Sequence[str], None] = 'ece472a6a39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = postgresql.ENUM('admin', 'patient', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('role', sa.Enum('admin', 'patient', name='role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'role')
    # ### end Alembic commands ###
