"""refertiaperto

Revision ID: c672fa3b65e3
Revises: 5f58ddc35e4b
Create Date: 2026-01-21 18:04:30.290367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c672fa3b65e3'
down_revision: Union[str, Sequence[str], None] = '5f58ddc35e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referti', sa.Column('aperto', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('referti', 'stato_referto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referti', sa.Column('stato_referto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('referti', 'aperto')
    # ### end Alembic commands ###
