"""agg reparti

Revision ID: c7ac117db4d0
Revises: 1f7581c79345
Create Date: 2026-03-16 19:22:07.100292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ac117db4d0'
down_revision: Union[str, Sequence[str], None] = '1f7581c79345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medici_reparti',
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('reparto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medici.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reparto_id'], ['reparti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medico_id', 'reparto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medici_reparti')
    # ### end Alembic commands ###
