"""label contatti

Revision ID: ca45eda798b6
Revises: 3c5d41e0c293
Create Date: 2026-02-20 20:16:00.898458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca45eda798b6'
down_revision: Union[str, Sequence[str], None] = '3c5d41e0c293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contatti_emergenza', sa.Column('nome_emergenza', sa.String(length=100), nullable=False))
    op.add_column('contatti_emergenza', sa.Column('numero_emergenza', sa.String(length=20), nullable=True))
    op.drop_column('contatti_emergenza', 'nome')
    op.drop_column('contatti_emergenza', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contatti_emergenza', sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('contatti_emergenza', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('contatti_emergenza', 'numero_emergenza')
    op.drop_column('contatti_emergenza', 'nome_emergenza')
    # ### end Alembic commands ###
