"""medicodatanascita

Revision ID: e09a24ab25a9
Revises: 319b491772c4
Create Date: 2026-03-04 18:05:06.263415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09a24ab25a9'
down_revision: Union[str, Sequence[str], None] = '319b491772c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medici', sa.Column('data_nascita', sa.Date(), nullable=True))
    op.alter_column('medici', 'codice_fiscale',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pazienti', 'codice_fiscale',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pazienti', 'codice_fiscale',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medici', 'codice_fiscale',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('medici', 'data_nascita')
    # ### end Alembic commands ###
