"""medico emailN

Revision ID: ebed0d742236
Revises: 1c0ae46028b3
Create Date: 2026-03-04 18:17:30.055977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebed0d742236'
down_revision: Union[str, Sequence[str], None] = '1c0ae46028b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medici', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medici', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
