"""leva età

Revision ID: ecb2afd0aa51
Revises: a76790c4f783
Create Date: 2026-03-02 16:33:12.514202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb2afd0aa51'
down_revision: Union[str, Sequence[str], None] = 'a76790c4f783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pazienti', 'eta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pazienti', sa.Column('eta', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
