"""noemail

Revision ID: ece472a6a39d
Revises: 11eb9bf2cd86
Create Date: 2026-02-07 17:44:12.903283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece472a6a39d'
down_revision: Union[str, Sequence[str], None] = '11eb9bf2cd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pazienti_email_key'), 'pazienti', type_='unique')
    op.create_unique_constraint(None, 'pazienti', ['account_id'])
    op.drop_column('pazienti', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pazienti', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pazienti', type_='unique')
    op.create_unique_constraint(op.f('pazienti_email_key'), 'pazienti', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
