"""tabellareparti

Revision ID: fb201b7fdb8f
Revises: e070e5206a30
Create Date: 2026-01-16 17:43:22.738057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb201b7fdb8f'
down_revision: Union[str, Sequence[str], None] = 'e070e5206a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('piano', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparti')
    # ### end Alembic commands ###
